name: Update GitHub Profile README

on:
  push:
    branches:
      - main # Запускать при каждом пуше в ветку main
  schedule:
    - cron: '0 0 * * *' # И по-прежнему обновлять каждую ночь в 00:00 UTC
  workflow_dispatch:
    # И возможность ручного запуска через UI

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4
        with:
          repository: 'ssnddsgnr/ssnddsgnr'
          token: ${{ secrets.PROFILE_UPDATE_TOKEN }}
          path: 'profile'

      - name: Checkout generator code
        uses: actions/checkout@v4
        with:
          path: 'generator'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Generator
        env:
          PROFILE_UPDATE_TOKEN: ${{ secrets.PROFILE_UPDATE_TOKEN }}
        run: |
          cd generator
          cargo run --release
          cp README.md ../profile/README.md

      - name: Commit and Push changes to main profile
        run: |
          cd profile
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: auto-update profile README via CI" && git push)
